#!/bin/bash
# Author: Jason Wieringa

TEMP_DIR=$(mktemp -d)
pushd $TEMP_DIR

echo "Download ruby-install package"
wget -O ruby-install-0.6.1.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.1.tar.gz

echo "Verify package is from postmodern"
wget https://raw.github.com/postmodern/ruby-install/master/pkg/ruby-install-0.6.1.tar.gz.asc
gpg --verify ruby-install-0.6.1.tar.gz.asc ruby-install-0.6.1.tar.gz

echo "Install ruby-installer"
tar -xzvf ruby-install-0.6.1.tar.gz
cd ruby-install-0.6.1/
sudo make install

popd
rm -rf $TEMP_DIR
